### ISSUE TITLE
RFP (Request for Proposals) : Support send runtime calls using wallets like metamask

### ISSUE THREAD

**Issue by hackfisher** [ringecosystem/collaboration#55]
This can be easily constructed by the runtime calls component and dispatch js SDK

**Comment by wuminzhe** [comment]
https://jsfiddle.net/wuminzhe/5qx0pcej/1/

**Comment by hackfisher** [comment]
This is for developer, not for app user, as we already have a solidity solution for it, let's move it to documentation.
