### ISSUE TITLE
Outdated information/link for/in KtonDAO docs

### ISSUE THREAD

**Issue by Laki389** [ringecosystem/collaboration#96]
Hello, I hope I'm reporting this issue in the appropriate place and manner.

https://docs.darwinia.network/community/orgs/ktondao/

 "On the Darwinia chains, users can deposit their RING for up to **36** months"
 
 It is 12 months since some weeks ago.
 
 Also, this link https://collator-staking.darwinia.network/ is the old, v1 staking website. :+1:

**Comment by Laki389** [comment]
@boundless-forest

**Comment by boundless-forest** [comment]
Nice catch, I'll update this later

**Comment by boundless-forest** [comment]
Done. updated https://docs.darwinia.network/community/orgs/ktondao/

**Comment by Laki389** [comment]
> Done. updated https://docs.darwinia.network/community/orgs/ktondao/

@boundless-forest 

Hi, i think in the updated doc it is still the v1 staking website.

v2 Ring staking website is https://collator-staking.ringdao.com/
